# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [4]:
%matplotlib inline
#%pip install seaborn

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[57, 21, 83, ..., 48, 30, 34],
       [ 2, 12, 75, ...,  4, 91, 68],
       [79, 78, 68, ..., 38, 87, 22],
       ...,
       [74, 76, 38, ..., 71, 60, 55],
       [25, 16, 41, ..., 69, 28, 91],
       [95, 55, 86, ..., 91, 96, 31]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [157]:
# small_A = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
new_A = np.random.permutation(A.T).T
new_A

array([[96, 26, 53, ..., 11, 77, 57],
       [14, 31, 45, ..., 66, 50,  2],
       [59, 67, 83, ..., 17, 47, 79],
       ...,
       [95, 82,  6, ..., 35, 50, 74],
       [ 6, 54, 51, ..., 48, 16, 25],
       [ 5, 50, 53, ...,  7,  6, 95]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [67]:
new_A = A[A[:,0::2].sum(axis = 1) > A[:,1::2].mean()]
new_A

array([[57, 21, 83, ..., 48, 30, 34],
       [ 2, 12, 75, ...,  4, 91, 68],
       [79, 78, 68, ..., 38, 87, 22],
       ...,
       [74, 76, 38, ..., 71, 60, 55],
       [25, 16, 41, ..., 69, 28, 91],
       [95, 55, 86, ..., 91, 96, 31]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [73]:
np.argmax(A.max(axis = 1) - A.min(axis = 1))

2

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [122]:
new_A = np.argsort(np.argsort(A, axis=None)).reshape(A.shape) + 1
new_A

array([[5698, 2171, 8340, ..., 4782, 2995, 3440],
       [ 223, 1195, 7500, ...,  450, 9138, 6847],
       [7940, 7875, 6829, ..., 3798, 8674, 2266],
       ...,
       [7400, 7590, 3806, ..., 7147, 5987, 5502],
       [2539, 1672, 4107, ..., 6919, 2837, 9168],
       [9563, 5540, 8623, ..., 9156, 9607, 3125]], dtype=int64)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [143]:
s = np.array([[1,2,3],[1,2,3],[5,3,3],[1,2,3]])
new_A = (s - s.min(axis = 1).reshape(-1,1)) / (s.max(axis = 1).reshape(-1,1) - s.min(axis = 1).reshape(-1,1))
new_A

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [1. , 0. , 0. ],
       [0. , 0.5, 1. ]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [173]:
base = A.reshape(1, *A.shape)
new_A = np.concatenate((base, 2*base, 3*base, 4*base, 5*base, 6*base, 7*base, 8*base, 9*base, 10*base))
print(new_A.shape)
new_A

(10, 200, 50)


array([[[ 57,  21,  83, ...,  48,  30,  34],
        [  2,  12,  75, ...,   4,  91,  68],
        [ 79,  78,  68, ...,  38,  87,  22],
        ...,
        [ 74,  76,  38, ...,  71,  60,  55],
        [ 25,  16,  41, ...,  69,  28,  91],
        [ 95,  55,  86, ...,  91,  96,  31]],

       [[114,  42, 166, ...,  96,  60,  68],
        [  4,  24, 150, ...,   8, 182, 136],
        [158, 156, 136, ...,  76, 174,  44],
        ...,
        [148, 152,  76, ..., 142, 120, 110],
        [ 50,  32,  82, ..., 138,  56, 182],
        [190, 110, 172, ..., 182, 192,  62]],

       [[171,  63, 249, ..., 144,  90, 102],
        [  6,  36, 225, ...,  12, 273, 204],
        [237, 234, 204, ..., 114, 261,  66],
        ...,
        [222, 228, 114, ..., 213, 180, 165],
        [ 75,  48, 123, ..., 207,  84, 273],
        [285, 165, 258, ..., 273, 288,  93]],

       ...,

       [[456, 168, 664, ..., 384, 240, 272],
        [ 16,  96, 600, ...,  32, 728, 544],
        [632, 624, 544, ..., 304, 696, 176

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [182]:
new_A = np.concatenate((A[:,0::2], A[:,1::2]), axis = 1)
new_A

array([[57, 83, 76, ..., 73, 48, 34],
       [ 2, 75, 25, ..., 90,  4, 68],
       [79, 68, 64, ...,  5, 38, 22],
       ...,
       [74, 38, 47, ..., 41, 71, 55],
       [25, 41, 30, ..., 64, 69, 91],
       [95, 86, 63, ..., 32, 91, 31]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [198]:
len(A[np.all(A > 5, axis = 1)])

8

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [217]:
new_A = np.mean(np.split(A, 10), axis = 0)
print(new_A.shape)
new_A

(20, 50)


array([[52.8, 41.7, 44.7, 42.8, 44. , 42. , 40.6, 37.9, 33.6, 46.4, 44.4,
        50.3, 49.8, 48.6, 58.3, 74.7, 58.7, 62.6, 44.7, 65.6, 57.3, 49.9,
        28.8, 43.1, 31.9, 48.8, 53.7, 39.4, 55.7, 56.1, 55.7, 34.1, 59.9,
        60. , 54.8, 46.5, 34.3, 39.2, 35.7, 65.7, 43.2, 59.6, 58.6, 58.3,
        53.2, 47.3, 40.4, 60.3, 40.8, 38.3],
       [41.3, 50.5, 55.3, 64.7, 62.4, 40.5, 60.7, 35.6, 50.6, 37.7, 52.5,
        43.1, 49.5, 53.7, 48. , 45.8, 45.9, 59.3, 45.9, 46.2, 43.3, 67.5,
        46.2, 40. , 52.4, 40.1, 43.6, 62.6, 40.8, 63.7, 49.3, 59.4, 42.2,
        66.7, 48.3, 33.2, 52.6, 61.4, 52.7, 59.1, 58.6, 75.3, 43.1, 55.9,
        60.4, 40.8, 55.7, 55.6, 53.9, 52.6],
       [51.1, 52.3, 57.5, 42.4, 57. , 64.6, 62.5, 64.4, 44.1, 42.9, 48.9,
        40.6, 26.9, 59.8, 59.9, 58.8, 44.9, 58.7, 50.1, 37.4, 42.9, 41.6,
        56.5, 44.5, 49.4, 48.6, 54.8, 62.7, 72.9, 29. , 33.2, 48.4, 40.2,
        60.7, 44.5, 65.8, 72.3, 41.1, 40.2, 35.1, 43. , 48.2, 54.4, 61.3,
        64. , 47.1, 45

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [251]:
_, ind = np.unique(A, return_index = True)
new_A = A.reshape((1, -1))[0][np.sort(ind)]
new_A

array([57, 21, 83, 44, 76, 20, 19, 84, 23, 42, 67,  1, 59,  7, 13, 53, 68,
       92, 77, 96, 43, 14, 70, 91, 38, 24, 98,  4, 39, 11, 82, 55, 15, 31,
       56, 86, 66, 26, 80, 73, 17, 48, 30, 34,  2, 12, 75, 60, 25, 36, 74,
        8, 46, 78, 88, 47, 45, 63, 27, 50, 71, 28, 72, 33, 37, 35, 99, 65,
       90, 54, 79, 64, 94,  3, 18, 87, 61, 41, 49, 16, 51, 85,  0, 97,  5,
       22, 58, 69,  9, 52, 95,  6, 93, 89, 81, 62, 10, 40, 29, 32])

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

In [260]:
np.linalg.norm(A - np.mean(A, axis = 0), axis = 1)

array([198.67676298, 189.88466539, 207.68850751, 193.36557643,
       211.93882643, 195.55767985, 207.71048637, 188.54794125,
       184.30845382, 184.32879903, 215.07790716, 220.55853225,
       195.13694204, 208.89450962, 212.41121945, 214.82526888,
       203.49367595, 179.20392337, 205.07129529, 197.90400741,
       200.47495143, 195.5838852 , 229.566213  , 188.69264996,
       214.83930308, 191.90019841, 215.09455165, 203.07724183,
       211.19471146, 203.4368112 , 223.37393794, 207.2756767 ,
       185.98079511, 210.77940163, 197.11236935, 198.67208196,
       208.23044002, 212.13155388, 205.01096593, 202.56069745,
       209.87004586, 197.93083678, 203.84000135, 202.92761308,
       222.07207422, 198.63900964, 206.40980149, 220.57671262,
       181.70934525, 206.13955503, 196.41332987, 218.16524964,
       190.5999112 , 218.0163667 , 208.86379808, 183.97485195,
       197.36363938, 200.84186852, 178.64192159, 206.37067657,
       206.58116117, 218.87228274, 210.44212067, 216.31

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [262]:
new_A = np.where(A < 50, A * 2, A * 3)
new_A

array([[171,  42, 249, ...,  96,  60,  68],
       [  4,  24, 225, ...,   8, 273, 204],
       [237, 234, 204, ...,  76, 261,  44],
       ...,
       [222, 228,  76, ..., 213, 180, 165],
       [ 50,  32,  82, ..., 207,  56, 273],
       [285, 165, 258, ..., 273, 288,  62]])

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

array([156.76666667, 146.03333333, 161.96666667, ..., 124.06666667,
        83.        ,  72.66666667])

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [ ]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 4, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [ ]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

2003

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [ ]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


-0.13580565475012618

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.