# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [2]:
%matplotlib inline
#%pip install seaborn

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[ 0, 71, 88, ..., 95,  6, 32],
       [ 2, 32, 80, ..., 50, 60, 23],
       [40, 76, 89, ..., 63, 43, 18],
       ...,
       [12, 27, 58, ..., 80, 13, 46],
       [30,  6, 10, ..., 84, 39, 63],
       [19, 87, 23, ..., 76, 16, 40]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [3]:
# small_A = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
new_A = np.random.permutation(A.T).T
new_A

array([[99, 32, 47, ...,  9, 33, 33],
       [67, 23, 11, ..., 48, 80, 32],
       [20, 18,  1, ..., 49, 98, 98],
       ...,
       [18, 46, 44, ..., 65, 61, 39],
       [25, 63,  4, ..., 97, 11, 87],
       [94, 40, 58, ..., 93,  7, 18]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [4]:
new_A = A[A[:,0::2].sum(axis = 1) > A[:,1::2].mean()]
new_A

array([[ 0, 71, 88, ..., 95,  6, 32],
       [ 2, 32, 80, ..., 50, 60, 23],
       [40, 76, 89, ..., 63, 43, 18],
       ...,
       [12, 27, 58, ..., 80, 13, 46],
       [30,  6, 10, ..., 84, 39, 63],
       [19, 87, 23, ..., 76, 16, 40]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [5]:
np.argmax(A.max(axis = 1) - A.min(axis = 1))

0

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [6]:
new_A = np.argsort(np.argsort(A, axis=None)).reshape(A.shape) + 1
new_A

array([[   1, 7171, 8851, ..., 9568,  693, 3211],
       [ 253, 3233, 8014, ..., 5068, 6053, 2349],
       [4062, 7604, 8977, ..., 6333, 4374, 1823],
       ...,
       [1214, 2696, 5834, ..., 8037, 1353, 4689],
       [3024,  638, 1044, ..., 8487, 3950, 6344],
       [1889, 8742, 2374, ..., 7646, 1621, 4045]], dtype=int64)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [7]:
s = np.array([[1,2,3],[1,2,3],[5,3,3],[1,2,3]])
new_A = (s - s.min(axis = 1).reshape(-1,1)) / (s.max(axis = 1).reshape(-1,1) - s.min(axis = 1).reshape(-1,1))
new_A

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [1. , 0. , 0. ],
       [0. , 0.5, 1. ]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [8]:
base = A.reshape(1, *A.shape)
new_A = np.concatenate((base, 2*base, 3*base, 4*base, 5*base, 6*base, 7*base, 8*base, 9*base, 10*base))
print(new_A.shape)
new_A

(10, 200, 50)


array([[[  0,  71,  88, ...,  95,   6,  32],
        [  2,  32,  80, ...,  50,  60,  23],
        [ 40,  76,  89, ...,  63,  43,  18],
        ...,
        [ 12,  27,  58, ...,  80,  13,  46],
        [ 30,   6,  10, ...,  84,  39,  63],
        [ 19,  87,  23, ...,  76,  16,  40]],

       [[  0, 142, 176, ..., 190,  12,  64],
        [  4,  64, 160, ..., 100, 120,  46],
        [ 80, 152, 178, ..., 126,  86,  36],
        ...,
        [ 24,  54, 116, ..., 160,  26,  92],
        [ 60,  12,  20, ..., 168,  78, 126],
        [ 38, 174,  46, ..., 152,  32,  80]],

       [[  0, 213, 264, ..., 285,  18,  96],
        [  6,  96, 240, ..., 150, 180,  69],
        [120, 228, 267, ..., 189, 129,  54],
        ...,
        [ 36,  81, 174, ..., 240,  39, 138],
        [ 90,  18,  30, ..., 252, 117, 189],
        [ 57, 261,  69, ..., 228,  48, 120]],

       ...,

       [[  0, 568, 704, ..., 760,  48, 256],
        [ 16, 256, 640, ..., 400, 480, 184],
        [320, 608, 712, ..., 504, 344, 144

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [9]:
new_A = np.concatenate((A[:,0::2], A[:,1::2]), axis = 1)
new_A

array([[ 0, 88, 33, ..., 83, 95, 32],
       [ 2, 80, 32, ..., 91, 50, 23],
       [40, 89, 98, ..., 96, 63, 18],
       ...,
       [12, 58, 39, ..., 27, 80, 46],
       [30, 10, 87, ..., 71, 84, 63],
       [19, 23, 18, ..., 32, 76, 40]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [10]:
len(A[np.all(A > 5, axis = 1)])

8

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [11]:
new_A = np.mean(np.split(A, 10), axis = 0)
print(new_A.shape)
new_A

(20, 50)


array([[56.2, 49. , 44.3, 38.1, 47.3, 41.7, 55.3, 39.8, 40.9, 52.8, 51.3,
        59.9, 33.5, 30.5, 47.4, 48.4, 49. , 60. , 50.1, 57.8, 51.3, 48.9,
        48.7, 51.7, 29.5, 60.7, 45.5, 28.4, 35.4, 29.5, 50.6, 60.5, 38.2,
        58.2, 47.5, 55.4, 51.6, 55.5, 50.3, 52.7, 57.2, 41.8, 49.3, 47.7,
        45.2, 53.5, 58.5, 70.1, 47.8, 61.1],
       [46.7, 48. , 62. , 38.5, 40.9, 44.2, 44.8, 38.8, 58.1, 53.2, 53.3,
        43.1, 56.9, 50.6, 42. , 38. , 36.9, 42. , 63.7, 57.5, 53.4, 54.1,
        34.8, 52. , 56.2, 54.4, 63.1, 38.4, 47. , 40.7, 51.3, 57.5, 50.4,
        71.5, 39.6, 55.9, 61.4, 49.4, 41.9, 53.4, 49.8, 52.2, 57.6, 52.5,
        44. , 51.9, 37.2, 36.3, 41.9, 53. ],
       [49.2, 37.9, 46.6, 37.6, 51.7, 43.3, 50.4, 44.9, 51.4, 49.7, 56.4,
        40.7, 27.7, 53.4, 60.5, 64.4, 53.1, 53. , 37.7, 47.8, 42.2, 54.3,
        33.7, 58.3, 43.5, 58.9, 34.6, 68.9, 47.1, 44.5, 43.5, 55.2, 70.3,
        65.5, 57.1, 49. , 32.4, 26.5, 60.6, 51.1, 59.6, 54.6, 61.8, 50.6,
        59.3, 60.2, 53

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [12]:
_, ind = np.unique(A, return_index = True)
new_A = A.reshape((1, -1))[0][np.sort(ind)]
new_A

array([ 0, 71, 88,  4, 33, 40, 97, 29, 35, 60, 37, 43,  9, 94, 83, 89, 67,
       66, 85, 28, 11, 55, 45, 47, 26, 91, 20, 58, 80, 98, 99, 56, 51, 95,
        6, 32,  2, 62, 10, 12, 70, 44, 22, 48, 93, 25, 86, 19, 41, 15, 30,
       13, 42, 57, 84, 16, 75,  8, 74, 38, 24, 50, 23, 76, 77, 34, 65, 49,
       61, 64, 68, 18, 54,  1, 82, 72, 92, 96, 63, 39, 31, 90, 36, 81, 79,
       27, 52, 53, 78,  3, 87, 73, 14, 69,  7, 17, 59, 21,  5, 46])

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

In [13]:
np.linalg.norm(A - np.mean(A, axis = 0), axis = 1)

array([200.8000963 , 189.11118072, 210.5219672 , 189.17679212,
       211.86113064, 203.19955383, 208.43180821, 188.18681855,
       216.95801132, 191.27323042, 199.39688733, 197.57218599,
       205.81403906, 202.71351379, 204.16835865, 198.85979653,
       199.11167388, 195.14317481, 209.87557903, 178.56757453,
       228.33924033, 221.3854753 , 196.70431789, 208.28237726,
       205.65971573, 226.5464603 , 221.04985563, 223.15003624,
       217.50404289, 206.842739  , 203.5778197 , 201.14621218,
       222.01339751, 198.87669214, 204.59430265, 205.72651427,
       198.94961341, 215.71510998, 212.41856952, 214.03704977,
       210.06243994, 198.53709647, 203.29468433, 193.5827954 ,
       215.13139863, 175.0061961 , 215.01015947, 199.07420394,
       190.43670517, 204.06371229, 202.9822866 , 200.59234451,
       204.7859582 , 220.45638724, 195.18911003, 223.7143238 ,
       220.86099401, 227.55025527, 202.43010812, 210.59228066,
       213.26016664, 183.55306774, 200.9507867 , 184.50

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [14]:
new_A = np.where(A < 50, A * 2, A * 3)
new_A

array([[  0, 213, 264, ..., 285,  12,  64],
       [  4,  64, 240, ..., 150, 180,  46],
       [ 80, 228, 267, ..., 189,  86,  36],
       ...,
       [ 24,  54, 174, ..., 240,  26,  92],
       [ 60,  12,  20, ..., 252,  78, 189],
       [ 38, 261,  46, ..., 228,  32,  80]])

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

In [27]:
flat_A = A.reshape((1, -1))[0]
def moving_avg(x, n):
    return np.convolve(x, np.ones(n)/n, mode='valid')
m_avg_3 = moving_avg(flat_A, 3)
m_avg_5 = moving_avg(flat_A, 5)
m_avg_10 = moving_avg(flat_A, 10)
m_avg_5 = np.concatenate((m_avg_5, np.zeros(m_avg_3.shape[0] - m_avg_5.shape[0])))
m_avg_10 = np.concatenate((m_avg_10, np.zeros(m_avg_3.shape[0] - m_avg_10.shape[0])))
sum = m_avg_3 + m_avg_5 + m_avg_10
print(m_avg_3.shape, sum.shape)
sum

(9998,) (9998,)


array([137.9       , 150.93333333, 140.66666667, ...,  71.46666667,
        32.33333333,  44.        ])

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [ ]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 4, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [ ]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

2003

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [ ]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


-0.13580565475012618

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.